JioCloudVPC/puppet-vpc

hiera/data/common.yaml
hiera/data/env/staging.yaml

Add proper usernames, passwords certs for staging

Added certs and usernames

---

debian/changelog

Increased the version of Puppet-vpc to ensure it gets pripority over the puppet-vpc already installed

Increased version to ease deployment of jiocloud packages

---

hiera/data/env/staging.yaml

Floating IP for staging server along with adding External MX routers

Add floating ip

---

hiera/data/env/staging.yaml

Changing endpoints of Dependent openstack services.

Changed endpoint of IAM/Compute/VPC

---

hiera/data/env/staging.yaml

Changing IAM endpoint for staging

Changed IAM endpoint

---

build_scripts/userdata_vrouter.txt

Added userdata_vrouter

---

hiera/data/env/staging.yaml
manifests/neutron/contrail/fip_pool.pp

Change from VPC Admin user to Service user

Change to service user

---

hiera/data/common.yaml

Small fix for issues during vagrant setup

Fix Common yaml for Vagrant setup

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml
hiera/data/role/cp.yaml
lib/facter/jiocloud_role.rb

This Pull request will change the dependency of packages from External reposutory to internal snapshots

Moved from external dependency to snapshots

---

Puppetfile
Vagrantfile
environment/vagrant-full.yaml
files/monitor_scripts/monitor_updates.sh
files/monitor_scripts/monitor_validation.sh
manifests/monitoring.pp
manifests/monitoring/base.pp
manifests/monitoring/cp.pp
manifests/monitoring/vpcanalytics.pp
manifests/monitoring/vpccfg.pp
manifests/monitoring/vpcctrl.pp
manifests/monitoring/vpcmonitor.pp
manifests/monitoring/vpcservice.pp
manifests/omd_client.pp
manifests/omd_server.pp
site.pp

This commit enables OMD Check MK Monitoring for VPC cluster

Omd monitoring

---

files/monitor_scripts/contrail_control_introspect.sh
manifests/monitoring/vpccfg.pp
manifests/monitoring/vpcctrl.pp

Monitor following items
* Status of XMPP connections
* Status of XMPP Peers
* Status of BGP Peers
* Status of IFMAP connection

[Pending testing with vagrant env] contrail control monitor script

---

files/monitor_scripts/contrail_control_introspect.sh

* show xmpp peer down notification only for 5 minute
* changes status error to critical

make service name unique

---

files/maybe-upgrade.sh
hiera/data/env/staging.yaml

Adding user domain project domain and version for puppet-neutron

Fix auth for Keystone 

---

Puppetfile
environment/vagrant-support.yaml
hiera/data/common.yaml
hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml
hiera/data/role/vpc-aws.yaml
manifests/contrail/ec2api.pp
manifests/haproxy/contrail.pp
site.pp

Enabling EC2API service for VPC Cluster

Add ec2api

---

build_scripts/make_userdata.sh

Fixes issues in userdata script

fix issues in userdata script

---

hiera/data/common.yaml
hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml

EC2api creates 5 networks for each subnet created.  Hence for staging we will be expanding it to 200 subnets and allow it to create 1000 networks.

Modify quota

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml
manifests/neutron/contrail.pp
manifests/neutron/contrail/new_iam_fip_pool.pp

Changes in Puppet provision of neutron due to changes in IAM authentication.

Changes iam int

---

files/monitor_scripts/contrail_config_introspect.sh
manifests/monitoring/vpccfg.pp
manifests/monitoring/vpcctrl.pp

Pull request for config monitoring

Config monitor - Cassandra and Zookeeper

---

hiera/data/env/staging.yaml

This ensures packages for vrouter are always updated to latest packages after each puppet run on compute node

Always ensure package is latest

---

files/monitor_scripts/contrail_config_introspect.sh

Correcting the zookeeper cluster stats. Now its monitoring the leader election port connection and the leader port connection.

Monito script correction and updation

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml

Changed snapshots

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml

New Snapshot of ec2api for JNT-39 and JNT-37

Added new snapshots

---

hiera/data/env/staging.yaml

Updated  quota for floating ip, vpc and subnets

Updating quota

---

hiera/data/env/staging.yaml

Reverting floating IP quota to 5

Reverting floating IP quota

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml

Updates Quota and Logs update in Middleware

Updated Snapshot ID

---

files/monitor_scripts/contrail_config_introspect.sh

Checking the specific port connections.

Correcting the script to specifically check for the port connections

---

hiera/data/env/production.yaml
hiera/data/snapshots/production.yaml
hiera/hiera.yaml

Production Deployment Configurations

Added Production Yaml

---

hiera/data/role/prod-cp.yaml
site.pp

In Production Compute team has changed the naming convention , adding to support for the same;

Added support for new naming convention of compute nodes

---

hiera/data/env/production.yaml

Adding a backup interface for vrouter, in case the primary does not exist

Added vrouter backup interface

---

manifests/contrail/ec2api.pp

Pull Request to enable logrotation for ec2api

Added logrotate for ec2api

---

hiera/data/env/staging.yaml

Changed Snapshot of Staging.yaml to fix JNT-78,64 etc/

Added snapshot for staging.yaml

---

hiera/data/env/staging.yaml

Staging changes for 3rd May tracked by bug JNT - 155

Bug JNT 150 tracked by JNT-155

---

hiera/data/env/production.yaml
hiera/data/env/staging.yaml

Removed DNS Entries from /etc/hosts and corrected keystone auth_url in contrail config

Corrected Configurations 

---

hiera/data/snapshots/production.yaml

Changing snapshot on for JNT-150

Production changes for JNT-150

---

hiera/data/env/staging.yaml

jnt_60 snapshot update for staging

jnt_60 snapshot update for staging

---

hiera/data/env/staging.yaml
templates/tests/corosync_check.sh.erb
templates/tests/pacemaker_check.sh.erb

Minor errors in  Pacemaker configs

Fixed minor errors

---

hiera/data/env/production.yaml

Pacemaker configs for production

Added Pacemaker configs to production .yaml

---

hiera/data/snapshots/production.yaml

Changing snapshot for JNT-149 production deployment.

Changing snapshot for JNT-149 production deployment

---

hiera/data/env/staging.yaml
hiera/data/snapshots/staging.yaml

Moved Snapshots of staging to ensure its similar to production

Move stag snapshot

---

hiera/data/snapshots/production.yaml

JNT-273 deploy to production

---

hiera/data/env/staging.yaml
manifests/neutron/contrail.pp

Adding new public subnet in staging

Added changes to incorporate new pub-subnet

---

hiera/data/env/staging.yaml

policy.json change to show vif_type in get_port result.
Closes-Bug: JNT-281

jnt-281 policy.json change to show vif_type

---

hiera/data/env/staging.yaml

Adding virtual ip in hiera

---

Puppetfile
hiera/data/env/production.yaml
hiera/data/env/staging.yaml

Changing Corosync Staging and production netmask

Ha subnet prod

---

hiera/data/role/vpc-analytics.yaml
manifests/contrail/analytics.pp
site.pp

These changes configure multi analytics node setup.

Multi analytics config

---

hiera/data/snapshots/staging.yaml

InfoSec requirement to Forward source IP to IAM

jnt 355 staging snapshot change

---

hiera/data/env/staging.yaml
manifests/neutron/contrail.pp

After this while implementing need to chang staging.yaml and production.yaml to set variable to true

Changes in neutron.conf it will add database/connection

---

hiera/data/env/staging.yaml

Add a specific role:advsvc to set context advsvc. By default every user has advsvc role.

adding patch to change policy.json file

---

environment/vagrant-full.yaml
hiera/data/common.yaml
hiera/data/env/vagrant-vbox.yaml

Vagrant should be seamlessly with new package builder repos

---

hiera/data/env/staging.yaml
hiera/data/env/vagrant-vbox.yaml
hiera/data/role/vpc-analytics.yaml
manifests/celery/celery.pp
manifests/rabbitmq.pp
manifests/system/apt.pp
manifests/zookeeper.pp
site.pp
templates/celery_beat_init.erb
templates/celery_worker_init.erb
templates/flowlogd_config.erb

This patch deploy celery worker and beat service with rabbitmq
and zookeeper cluster in analytics node.

celery with rabbitmq and zookeeper for flowlog
